/* Copyright © 2024 Iluvatar CoreX. All rights reserved.                                                            */
/* Copyright Declaration: This software, including all of its code and documentation, except for the third-party    */
/* software it contains, is a copyrighted work of Shanghai Iluvatar CoreX Semiconductor Co., Ltd. and its           */
/* affiliates (“Iluvatar CoreX”) in accordance with the PRC Copyright Law and relevant international treaties,      */
/* and all rights contained therein are enjoyed by Iluvatar CoreX. No user of this software shall have any right,   */
/* ownership or interest in this software and any use of this software shall be in compliance with the terms        */
/* and conditions of the End User License Agreement.                                                                */
#ifndef __IXDCGMFIELDS_H__
#define __IXDCGMFIELDS_H__


#include <stdbool.h>

#ifdef __cplusplus
extern "C"
{
#endif

#define IXDCGM_FT_BINARY 'b'
#define IXDCGM_FT_DOUBLE 'd'
#define IXDCGM_FT_INT64 'i'
#define IXDCGM_FT_STRING 's'
#define IXDCGM_FT_TIMESTAMP 't'
#define IXDCGM_FS_GLOBAL 0
#define IXDCGM_FS_ENTITY 1
#define IXDCGM_FS_DEVICE IXDCGM_FS_ENTITY
#define IXDCGM_CUDA_COMPUTE_CAPABILITY_MAJOR(x) ((uint64_t)(x) & 0xFFFF0000)
#define IXDCGM_CUDA_COMPUTE_CAPABILITY_MINOR(x) ((uint64_t)(x) & 0x0000FFFF)
#define IXDCGM_CLOCKS_THROTTLE_REASON_GPU_IDLE 0x0000000000000001LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_CLOCKS_SETTING 0x0000000000000002LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_SW_POWER_CAP 0x0000000000000004LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_HW_SLOWDOWN 0x0000000000000008LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_SYNC_BOOST 0x0000000000000010LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_SW_THERMAL 0x0000000000000020LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_HW_THERMAL 0x0000000000000040LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_HW_POWER_BRAKE 0x0000000000000080LL
#define IXDCGM_CLOCKS_THROTTLE_REASON_DISPLAY_CLOCKS 0x0000000000000100LL
#define IXDCGM_FI_UNKNOWN 0
#define IXDCGM_FI_DRIVER_VERSION 1
#define IXDCGM_FI_NVML_VERSION 2
#define IXDCGM_FI_PROCESS_NAME 3
#define IXDCGM_FI_DEV_COUNT 4
#define IXDCGM_FI_CUDA_DRIVER_VERSION 5
#define IXDCGM_FI_DEV_NAME 50
#define IXDCGM_FI_DEV_BRAND 51
#define IXDCGM_FI_DEV_NVML_INDEX 52
#define IXDCGM_FI_DEV_SERIAL 53
#define IXDCGM_FI_DEV_UUID 54
#define IXDCGM_FI_DEV_MINOR_NUMBER 55
#define IXDCGM_FI_DEV_OEM_INFOROM_VER 56
#define IXDCGM_FI_DEV_PCI_BUSID 57
#define IXDCGM_FI_DEV_PCI_COMBINED_ID 58
#define IXDCGM_FI_DEV_PCI_SUBSYS_ID 59
#define IXDCGM_FI_GPU_TOPOLOGY_PCI 60
#define IXDCGM_FI_GPU_TOPOLOGY_NVLINK 61
#define IXDCGM_FI_GPU_TOPOLOGY_AFFINITY 62
#define IXDCGM_FI_DEV_CUDA_COMPUTE_CAPABILITY 63
#define IXDCGM_FI_DEV_COMPUTE_MODE 65
#define IXDCGM_FI_DEV_PERSISTENCE_MODE 66
#define IXDCGM_FI_DEV_MIG_MODE 67
#define IXDCGM_FI_DEV_CUDA_VISIBLE_DEVICES_STR 68
#define IXDCGM_FI_DEV_MIG_MAX_SLICES 69
#define IXDCGM_FI_DEV_CPU_AFFINITY_0 70
#define IXDCGM_FI_DEV_CPU_AFFINITY_1 71
#define IXDCGM_FI_DEV_CPU_AFFINITY_2 72
#define IXDCGM_FI_DEV_CPU_AFFINITY_3 73
#define IXDCGM_FI_DEV_CC_MODE 74
#define IXDCGM_FI_DEV_MIG_ATTRIBUTES 75
#define IXDCGM_FI_DEV_MIG_GI_INFO 76
#define IXDCGM_FI_DEV_MIG_CI_INFO 77
#define IXDCGM_FI_DEV_ECC_INFOROM_VER 80
#define IXDCGM_FI_DEV_POWER_INFOROM_VER 81
#define IXDCGM_FI_DEV_INFOROM_IMAGE_VER 82
#define IXDCGM_FI_DEV_INFOROM_CONFIG_CHECK 83
#define IXDCGM_FI_DEV_INFOROM_CONFIG_VALID 84
#define IXDCGM_FI_DEV_VBIOS_VERSION 85
#define IXDCGM_FI_DEV_MEM_AFFINITY_0 86
#define IXDCGM_FI_DEV_MEM_AFFINITY_1 87
#define IXDCGM_FI_DEV_MEM_AFFINITY_2 88
#define IXDCGM_FI_DEV_MEM_AFFINITY_3 89
#define IXDCGM_FI_DEV_BAR1_TOTAL 90
#define IXDCGM_FI_SYNC_BOOST 91
#define IXDCGM_FI_DEV_BAR1_USED 92
#define IXDCGM_FI_DEV_BAR1_FREE 93
#define IXDCGM_FI_DEV_SM_CLOCK 100
#define IXDCGM_FI_DEV_MEM_CLOCK 101
#define IXDCGM_FI_DEV_VIDEO_CLOCK 102
#define IXDCGM_FI_DEV_APP_SM_CLOCK 110
#define IXDCGM_FI_DEV_APP_MEM_CLOCK 111
#define IXDCGM_FI_DEV_CLOCK_THROTTLE_REASONS 112
#define IXDCGM_FI_DEV_MAX_SM_CLOCK 113
#define IXDCGM_FI_DEV_MAX_MEM_CLOCK 114
#define IXDCGM_FI_DEV_MAX_VIDEO_CLOCK 115
#define IXDCGM_FI_DEV_AUTOBOOST 120
#define IXDCGM_FI_DEV_SUPPORTED_CLOCKS 130
#define IXDCGM_FI_DEV_MEMORY_TEMP 140
#define IXDCGM_FI_DEV_GPU_TEMP 150
#define IXDCGM_FI_DEV_MEM_MAX_OP_TEMP 151
#define IXDCGM_FI_DEV_GPU_MAX_OP_TEMP 152
#define IXDCGM_FI_DEV_POWER_USAGE 155
#define IXDCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION 156
#define IXDCGM_FI_DEV_POWER_USAGE_INSTANT 157
#define IXDCGM_FI_DEV_SLOWDOWN_TEMP 158
#define IXDCGM_FI_DEV_SHUTDOWN_TEMP 159
#define IXDCGM_FI_DEV_POWER_MGMT_LIMIT 160
#define IXDCGM_FI_DEV_POWER_MGMT_LIMIT_MIN 161
#define IXDCGM_FI_DEV_POWER_MGMT_LIMIT_MAX 162
#define IXDCGM_FI_DEV_POWER_MGMT_LIMIT_DEF 163
#define IXDCGM_FI_DEV_ENFORCED_POWER_LIMIT 164
#define IXDCGM_FI_DEV_PSTATE 190
#define IXDCGM_FI_DEV_FAN_SPEED 191
#define IXDCGM_FI_DEV_PCIE_TX_THROUGHPUT 200
#define IXDCGM_FI_DEV_PCIE_RX_THROUGHPUT 201
#define IXDCGM_FI_DEV_PCIE_REPLAY_COUNTER 202
#define IXDCGM_FI_DEV_GPU_UTIL 203
#define IXDCGM_FI_DEV_MEM_COPY_UTIL 204
#define IXDCGM_FI_DEV_ACCOUNTING_DATA 205
#define IXDCGM_FI_DEV_ENC_UTIL 206
#define IXDCGM_FI_DEV_DEC_UTIL 207
#define IXDCGM_FI_DEV_XID_ERRORS 230
#define IXDCGM_FI_DEV_PCIE_MAX_LINK_GEN 235
#define IXDCGM_FI_DEV_PCIE_MAX_LINK_WIDTH 236
#define IXDCGM_FI_DEV_PCIE_LINK_GEN 237
#define IXDCGM_FI_DEV_PCIE_LINK_WIDTH 238
#define IXDCGM_FI_DEV_POWER_VIOLATION 240
#define IXDCGM_FI_DEV_THERMAL_VIOLATION 241
#define IXDCGM_FI_DEV_SYNC_BOOST_VIOLATION 242
#define IXDCGM_FI_DEV_BOARD_LIMIT_VIOLATION 243
#define IXDCGM_FI_DEV_LOW_UTIL_VIOLATION 244
#define IXDCGM_FI_DEV_RELIABILITY_VIOLATION 245
#define IXDCGM_FI_DEV_TOTAL_APP_CLOCKS_VIOLATION 246
#define IXDCGM_FI_DEV_TOTAL_BASE_CLOCKS_VIOLATION 247
#define IXDCGM_FI_DEV_FB_TOTAL 250
#define IXDCGM_FI_DEV_FB_FREE 251
#define IXDCGM_FI_DEV_FB_USED 252
#define IXDCGM_FI_DEV_FB_RESERVED 253
#define IXDCGM_FI_DEV_FB_USED_PERCENT 254
#define IXDCGM_FI_DEV_ECC_CURRENT 300
#define IXDCGM_FI_DEV_ECC_PENDING 301
#define IXDCGM_FI_DEV_ECC_SBE_VOL_TOTAL 310
#define IXDCGM_FI_DEV_ECC_DBE_VOL_TOTAL 311
#define IXDCGM_FI_DEV_ECC_SBE_AGG_TOTAL 312
#define IXDCGM_FI_DEV_ECC_DBE_AGG_TOTAL 313
#define IXDCGM_FI_DEV_ECC_SBE_VOL_L1 314
#define IXDCGM_FI_DEV_ECC_DBE_VOL_L1 315
#define IXDCGM_FI_DEV_ECC_SBE_VOL_L2 316
#define IXDCGM_FI_DEV_ECC_DBE_VOL_L2 317
#define IXDCGM_FI_DEV_ECC_SBE_VOL_DEV 318
#define IXDCGM_FI_DEV_ECC_DBE_VOL_DEV 319
#define IXDCGM_FI_DEV_ECC_SBE_VOL_REG 320
#define IXDCGM_FI_DEV_ECC_DBE_VOL_REG 321
#define IXDCGM_FI_DEV_ECC_SBE_VOL_TEX 322
#define IXDCGM_FI_DEV_ECC_DBE_VOL_TEX 323
#define IXDCGM_FI_DEV_ECC_SBE_AGG_L1 324
#define IXDCGM_FI_DEV_ECC_DBE_AGG_L1 325
#define IXDCGM_FI_DEV_ECC_SBE_AGG_L2 326
#define IXDCGM_FI_DEV_ECC_DBE_AGG_L2 327
#define IXDCGM_FI_DEV_ECC_SBE_AGG_DEV 328
#define IXDCGM_FI_DEV_ECC_DBE_AGG_DEV 329
#define IXDCGM_FI_DEV_ECC_SBE_AGG_REG 330
#define IXDCGM_FI_DEV_ECC_DBE_AGG_REG 331
#define IXDCGM_FI_DEV_ECC_SBE_AGG_TEX 332
#define IXDCGM_FI_DEV_ECC_DBE_AGG_TEX 333
#define IXDCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_MAX 385
#define IXDCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_HIGH 386
#define IXDCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_PARTIAL 387
#define IXDCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_LOW 388
#define IXDCGM_FI_DEV_BANKS_REMAP_ROWS_AVAIL_NONE 389
#define IXDCGM_FI_DEV_RETIRED_SBE 390
#define IXDCGM_FI_DEV_RETIRED_DBE 391
#define IXDCGM_FI_DEV_RETIRED_PENDING 392
#define IXDCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS 393
#define IXDCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS 394
#define IXDCGM_FI_DEV_ROW_REMAP_FAILURE 395
#define IXDCGM_FI_DEV_ROW_REMAP_PENDING 396
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L0 400
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L1 401
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L2 402
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L3 403
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L4 404
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L5 405
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL 409
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L0 410
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L1 411
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L2 412
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L3 413
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L4 414
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L5 415
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL 419
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L0 420
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L1 421
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L2 422
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L3 423
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L4 424
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L5 425
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL 429
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L0 430
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L1 431
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L2 432
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L3 433
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L4 434
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L5 435
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL 439
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L0 440
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L1 441
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L2 442
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L3 443
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L4 444
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L5 445
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL 449
#define IXDCGM_FI_DEV_GPU_NVLINK_ERRORS 450
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L6 451
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L7 452
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L8 453
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L9 454
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L10 455
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L11 456
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L6 457
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L7 458
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L8 459
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L9 460
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L10 461
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L11 462
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L6 463
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L7 464
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L8 465
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L9 466
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L10 467
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L11 468
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L6 469
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L7 470
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L8 471
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L9 472
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L10 473
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L11 474
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L6 475
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L7 476
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L8 477
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L9 478
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L10 479
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L11 480
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L12 406
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L13 407
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L14 408
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L15 481
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L16 482
#define IXDCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_L17 483
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L12 416
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L13 417
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L14 418
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L15 484
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L16 485
#define IXDCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_L17 486
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L12 426
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L13 427
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L14 428
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L15 487
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L16 488
#define IXDCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_L17 489
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L12 436
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L13 437
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L14 438
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L15 491
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L16 492
#define IXDCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_L17 493
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L12 446
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L13 447
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L14 448
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L15 494
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L16 495
#define IXDCGM_FI_DEV_NVLINK_BANDWIDTH_L17 496
#define IXDCGM_FI_DEV_VIRTUAL_MODE 500
#define IXDCGM_FI_DEV_SUPPORTED_TYPE_INFO 501
#define IXDCGM_FI_DEV_CREATABLE_VGPU_TYPE_IDS 502
#define IXDCGM_FI_DEV_VGPU_INSTANCE_IDS 503
#define IXDCGM_FI_DEV_VGPU_UTILIZATIONS 504
#define IXDCGM_FI_DEV_VGPU_PER_PROCESS_UTILIZATION 505
#define IXDCGM_FI_DEV_ENC_STATS 506
#define IXDCGM_FI_DEV_FBC_STATS 507
#define IXDCGM_FI_DEV_FBC_SESSIONS_INFO 508
#define IXDCGM_FI_DEV_SUPPORTED_VGPU_TYPE_IDS 509
#define IXDCGM_FI_DEV_VGPU_TYPE_INFO 510
#define IXDCGM_FI_DEV_VGPU_TYPE_NAME 511
#define IXDCGM_FI_DEV_VGPU_TYPE_CLASS 512
#define IXDCGM_FI_DEV_VGPU_TYPE_LICENSE 513
#define IXDCGM_FI_DEV_VGPU_VM_ID 520
#define IXDCGM_FI_DEV_VGPU_VM_NAME 521
#define IXDCGM_FI_DEV_VGPU_TYPE 522
#define IXDCGM_FI_DEV_VGPU_UUID 523
#define IXDCGM_FI_DEV_VGPU_DRIVER_VERSION 524
#define IXDCGM_FI_DEV_VGPU_MEMORY_USAGE 525
#define IXDCGM_FI_DEV_VGPU_LICENSE_STATUS 526
#define IXDCGM_FI_DEV_VGPU_FRAME_RATE_LIMIT 527
#define IXDCGM_FI_DEV_VGPU_ENC_STATS 528
#define IXDCGM_FI_DEV_VGPU_ENC_SESSIONS_INFO 529
#define IXDCGM_FI_DEV_VGPU_FBC_STATS 530
#define IXDCGM_FI_DEV_VGPU_FBC_SESSIONS_INFO 531
#define IXDCGM_FI_DEV_VGPU_INSTANCE_LICENSE_STATE 532
#define IXDCGM_FI_DEV_VGPU_PCI_ID 533
#define IXDCGM_FI_DEV_VGPU_VM_GPU_INSTANCE_ID 534
#define IXDCGM_FI_FIRST_VGPU_FIELD_ID 520
#define IXDCGM_FI_LAST_VGPU_FIELD_ID 570
#define IXDCGM_FI_MAX_VGPU_FIELDS IXDCGM_FI_LAST_VGPU_FIELD_ID - IXDCGM_FI_FIRST_VGPU_FIELD_ID
#define IXDCGM_FI_INTERNAL_FIELDS_0_START 600
#define IXDCGM_FI_INTERNAL_FIELDS_0_END 699
#define IXDCGM_FI_FIRST_NVSWITCH_FIELD_ID 700
#define IXDCGM_FI_DEV_NVSWITCH_VOLTAGE_MVOLT 701
#define IXDCGM_FI_DEV_NVSWITCH_CURRENT_IDDQ 702
#define IXDCGM_FI_DEV_NVSWITCH_CURRENT_IDDQ_REV 703
#define IXDCGM_FI_DEV_NVSWITCH_CURRENT_IDDQ_DVDD 704
#define IXDCGM_FI_DEV_NVSWITCH_LINK_THROUGHPUT_TX 780
#define IXDCGM_FI_DEV_NVSWITCH_LINK_THROUGHPUT_RX 781
#define IXDCGM_FI_DEV_NVSWITCH_LINK_FATAL_ERRORS 782
#define IXDCGM_FI_DEV_NVSWITCH_LINK_NON_FATAL_ERRORS 783
#define IXDCGM_FI_DEV_NVSWITCH_LINK_REPLAY_ERRORS 784
#define IXDCGM_FI_DEV_NVSWITCH_LINK_RECOVERY_ERRORS 785
#define IXDCGM_FI_DEV_NVSWITCH_LINK_FLIT_ERRORS 786
#define IXDCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS 787
#define IXDCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS 788
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_LOW_VC0 789
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_LOW_VC1 790
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_LOW_VC2 791
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_LOW_VC3 792
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_MEDIUM_VC0 793
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_MEDIUM_VC1 794
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_MEDIUM_VC2 795
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_MEDIUM_VC3 796
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_HIGH_VC0 797
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_HIGH_VC1 798
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_HIGH_VC2 799
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_HIGH_VC3 800
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_PANIC_VC0 801
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_PANIC_VC1 802
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_PANIC_VC2 803
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_PANIC_VC3 804
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC0 805
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC1 806
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC2 807
#define IXDCGM_FI_DEV_NVSWITCH_LINK_LATENCY_COUNT_VC3 808
#define IXDCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE0 809
#define IXDCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE1 810
#define IXDCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE2 811
#define IXDCGM_FI_DEV_NVSWITCH_LINK_CRC_ERRORS_LANE3 812
#define IXDCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE0 813
#define IXDCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE1 814
#define IXDCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE2 815
#define IXDCGM_FI_DEV_NVSWITCH_LINK_ECC_ERRORS_LANE3 816
#define IXDCGM_FI_DEV_NVSWITCH_FATAL_ERRORS 856
#define IXDCGM_FI_DEV_NVSWITCH_NON_FATAL_ERRORS 857
#define IXDCGM_FI_DEV_NVSWITCH_TEMPERATURE_CURRENT 858
#define IXDCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SLOWDOWN 859
#define IXDCGM_FI_DEV_NVSWITCH_TEMPERATURE_LIMIT_SHUTDOWN 860
#define IXDCGM_FI_DEV_NVSWITCH_THROUGHPUT_TX 861
#define IXDCGM_FI_DEV_NVSWITCH_THROUGHPUT_RX 862
#define IXDCGM_FI_DEV_NVSWITCH_PHYS_ID 863
#define IXDCGM_FI_DEV_NVSWITCH_RESET_REQUIRED 864
#define IXDCGM_FI_DEV_NVSWITCH_LINK_ID 865
#define IXDCGM_FI_DEV_NVSWITCH_PCIE_DOMAIN 866
#define IXDCGM_FI_DEV_NVSWITCH_PCIE_BUS 867
#define IXDCGM_FI_DEV_NVSWITCH_PCIE_DEVICE 868
#define IXDCGM_FI_DEV_NVSWITCH_PCIE_FUNCTION 869
#define IXDCGM_FI_DEV_NVSWITCH_LINK_STATUS 870
#define IXDCGM_FI_DEV_NVSWITCH_LINK_TYPE 871
#define IXDCGM_FI_DEV_NVSWITCH_LINK_REMOTE_PCIE_DOMAIN 872
#define IXDCGM_FI_DEV_NVSWITCH_LINK_REMOTE_PCIE_BUS 873
#define IXDCGM_FI_DEV_NVSWITCH_LINK_REMOTE_PCIE_DEVICE 874
#define IXDCGM_FI_DEV_NVSWITCH_LINK_REMOTE_PCIE_FUNCTION 875
#define IXDCGM_FI_DEV_NVSWITCH_LINK_DEVICE_LINK_ID 876
#define IXDCGM_FI_DEV_NVSWITCH_LINK_DEVICE_LINK_SID 877
#define IXDCGM_FI_DEV_NVSWITCH_LINK_DEVICE_UUID 878
#define IXDCGM_FI_LAST_NVSWITCH_FIELD_ID 899
#define IXDCGM_FI_MAX_NVSWITCH_FIELDS IXDCGM_FI_LAST_NVSWITCH_FIELD_ID - IXDCGM_FI_FIRST_NVSWITCH_FIELD_ID + 1
#define IXDCGM_FI_PROF_GR_ENGINE_ACTIVE 1001
#define IXDCGM_FI_PROF_SM_ACTIVE 1002
#define IXDCGM_FI_PROF_SM_OCCUPANCY 1003
#define IXDCGM_FI_PROF_PIPE_TENSOR_ACTIVE 1004
#define IXDCGM_FI_PROF_DRAM_ACTIVE 1005
#define IXDCGM_FI_PROF_PIPE_FP64_ACTIVE 1006
#define IXDCGM_FI_PROF_PIPE_FP32_ACTIVE 1007
#define IXDCGM_FI_PROF_PIPE_FP16_ACTIVE 1008
#define IXDCGM_FI_PROF_PCIE_TX_BYTES 1009
#define IXDCGM_FI_PROF_PCIE_RX_BYTES 1010
#define IXDCGM_FI_PROF_NVLINK_TX_BYTES 1011
#define IXDCGM_FI_PROF_NVLINK_RX_BYTES 1012
#define IXDCGM_FI_PROF_PIPE_TENSOR_IMMA_ACTIVE 1013
#define IXDCGM_FI_PROF_PIPE_TENSOR_HMMA_ACTIVE 1014
#define IXDCGM_FI_PROF_PIPE_TENSOR_DFMA_ACTIVE 1015
#define IXDCGM_FI_PROF_PIPE_INT_ACTIVE 1016
#define IXDCGM_FI_PROF_NVDEC0_ACTIVE 1017
#define IXDCGM_FI_PROF_NVDEC1_ACTIVE 1018
#define IXDCGM_FI_PROF_NVDEC2_ACTIVE 1019
#define IXDCGM_FI_PROF_NVDEC3_ACTIVE 1020
#define IXDCGM_FI_PROF_NVDEC4_ACTIVE 1021
#define IXDCGM_FI_PROF_NVDEC5_ACTIVE 1022
#define IXDCGM_FI_PROF_NVDEC6_ACTIVE 1023
#define IXDCGM_FI_PROF_NVDEC7_ACTIVE 1024
#define IXDCGM_FI_PROF_NVJPG0_ACTIVE 1025
#define IXDCGM_FI_PROF_NVJPG1_ACTIVE 1026
#define IXDCGM_FI_PROF_NVJPG2_ACTIVE 1027
#define IXDCGM_FI_PROF_NVJPG3_ACTIVE 1028
#define IXDCGM_FI_PROF_NVJPG4_ACTIVE 1029
#define IXDCGM_FI_PROF_NVJPG5_ACTIVE 1030
#define IXDCGM_FI_PROF_NVJPG6_ACTIVE 1031
#define IXDCGM_FI_PROF_NVJPG7_ACTIVE 1032
#define IXDCGM_FI_PROF_NVOFA0_ACTIVE 1033
#define IXDCGM_FI_PROF_NVLINK_L0_TX_BYTES 1040
#define IXDCGM_FI_PROF_NVLINK_L0_RX_BYTES 1041
#define IXDCGM_FI_PROF_NVLINK_L1_TX_BYTES 1042
#define IXDCGM_FI_PROF_NVLINK_L1_RX_BYTES 1043
#define IXDCGM_FI_PROF_NVLINK_L2_TX_BYTES 1044
#define IXDCGM_FI_PROF_NVLINK_L2_RX_BYTES 1045
#define IXDCGM_FI_PROF_NVLINK_L3_TX_BYTES 1046
#define IXDCGM_FI_PROF_NVLINK_L3_RX_BYTES 1047
#define IXDCGM_FI_PROF_NVLINK_L4_TX_BYTES 1048
#define IXDCGM_FI_PROF_NVLINK_L4_RX_BYTES 1049
#define IXDCGM_FI_PROF_NVLINK_L5_TX_BYTES 1050
#define IXDCGM_FI_PROF_NVLINK_L5_RX_BYTES 1051
#define IXDCGM_FI_PROF_NVLINK_L6_TX_BYTES 1052
#define IXDCGM_FI_PROF_NVLINK_L6_RX_BYTES 1053
#define IXDCGM_FI_PROF_NVLINK_L7_TX_BYTES 1054
#define IXDCGM_FI_PROF_NVLINK_L7_RX_BYTES 1055
#define IXDCGM_FI_PROF_NVLINK_L8_TX_BYTES 1056
#define IXDCGM_FI_PROF_NVLINK_L8_RX_BYTES 1057
#define IXDCGM_FI_PROF_NVLINK_L9_TX_BYTES 1058
#define IXDCGM_FI_PROF_NVLINK_L9_RX_BYTES 1059
#define IXDCGM_FI_PROF_NVLINK_L10_TX_BYTES 1060
#define IXDCGM_FI_PROF_NVLINK_L10_RX_BYTES 1061
#define IXDCGM_FI_PROF_NVLINK_L11_TX_BYTES 1062
#define IXDCGM_FI_PROF_NVLINK_L11_RX_BYTES 1063
#define IXDCGM_FI_PROF_NVLINK_L12_TX_BYTES 1064
#define IXDCGM_FI_PROF_NVLINK_L12_RX_BYTES 1065
#define IXDCGM_FI_PROF_NVLINK_L13_TX_BYTES 1066
#define IXDCGM_FI_PROF_NVLINK_L13_RX_BYTES 1067
#define IXDCGM_FI_PROF_NVLINK_L14_TX_BYTES 1068
#define IXDCGM_FI_PROF_NVLINK_L14_RX_BYTES 1069
#define IXDCGM_FI_PROF_NVLINK_L15_TX_BYTES 1070
#define IXDCGM_FI_PROF_NVLINK_L15_RX_BYTES 1071
#define IXDCGM_FI_PROF_NVLINK_L16_TX_BYTES 1072
#define IXDCGM_FI_PROF_NVLINK_L16_RX_BYTES 1073
#define IXDCGM_FI_PROF_NVLINK_L17_TX_BYTES 1074
#define IXDCGM_FI_PROF_NVLINK_L17_RX_BYTES 1075
#define IXDCGM_FI_PROF_NVLINK_THROUGHPUT_FIRST IXDCGM_FI_PROF_NVLINK_L0_TX_BYTES
#define IXDCGM_FI_PROF_NVLINK_THROUGHPUT_LAST IXDCGM_FI_PROF_NVLINK_L17_RX_BYTES
#define IXDCGM_FI_MAX_FIELDS 1076

    typedef enum ixdcgm_field_entity_group_t
    {
        IXDCGM_FE_NONE = 0, /*!< Field is not associated with an entity. Field scope should be IXDCGM_FS_GLOBAL */
        IXDCGM_FE_GPU,      /*!< Field is associated with a GPU entity */
        IXDCGM_FE_VGPU,     /*!< Field is associated with a VGPU entity */
        IXDCGM_FE_SWITCH,   /*!< Field is associated with a Switch entity */
        IXDCGM_FE_GPU_I,    /*!< Field is associated with a GPU Instance entity */
        IXDCGM_FE_GPU_CI,   /*!< Field is associated with a GPU Compute Instance entity */
        IXDCGM_FE_LINK,     /*!< Field is associated with an NVLink */
        IXDCGM_FE_CPU,      /*!< Field is associated with a CPU node */
        IXDCGM_FE_CPU_CORE, /*!< Field is associated with a CPU */

        IXDCGM_FE_COUNT /*!< Number of elements in this enumeration. Keep this entry last */
    } ixdcgm_field_entity_group_t;
    typedef unsigned int ixdcgm_field_eid_t;

    typedef struct
    {
        char shortName[10]; /*!< Short name corresponding to field. This short name is used to identify columns in dmon
                                 output.*/
        char  unit[4];      /*!< The unit of value. Eg: C(elsius), W(att), MB/s*/
        short width;        /*!< Maximum width/number of digits that a value for field can have.*/
    } ixdcgm_field_output_format_t, *ixdcgm_field_output_format_p;

    typedef struct
    {
        unsigned short fieldId;     /*!< Field identifier. IXDCGM_FI_? #define */
        char           fieldType;   /*!< Field type. IXDCGM_FT_? #define */
        unsigned char  size;        /*!< field size in bytes (raw value size). 0=variable (like IXDCGM_FT_STRING) */
        char           tag[48];     /*!< Tag for this field for serialization like 'device_temperature' */
        int            scope;       /*!< Field scope. IXDCGM_FS_? #define of this field's association */
        int            nvmlFieldId; /*!< Optional NVML field this DCGM field maps to. 0 = no mapping.
                                         Otherwise, this should be a NVML_FI_? #define from nvml.h */
        ixdcgm_field_entity_group_t
            entityLevel; /*!< Field entity level. IXDCGM_FE_? specifying at what level the field is queryable */

        ixdcgm_field_output_format_p valueFormat; /*!< pointer to the structure that holds the formatting the
                                                     values for fields */
    } ixdcgm_field_meta_t;

    typedef const ixdcgm_field_meta_t* ixdcgm_field_meta_p;

    int __attribute((visibility("default"))) ixdcgmFieldsInit(void);
    int __attribute((visibility("default"))) ixdcgmFieldsTerm(void);

    ixdcgm_field_meta_p __attribute((visibility("default"))) ixdcgmFieldGetById(unsigned short fieldId);

    bool ixdcgmIsFieldSupported(unsigned short fieldId);
    const char __attribute((visibility("default"))) *ixdcgmFieldsGetEntityGroupString(ixdcgm_field_entity_group_t entityGroupId);

#ifdef __cplusplus
}
#endif

#endif  // end of __IXDCGMFIELDS_H__