/*
Copyright (c) 2024, Shanghai Iluvatar CoreX Semiconductor Co., Ltd.
All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package ixdcgm

/*
#include "include/dcgm_agent.h"
#include "include/dcgm_structs.h"
*/
import "C"

const (
	DCGM_FI_UNKNOWN                         Short = C.DCGM_FI_UNKNOWN
	DCGM_FI_DRIVER_VERSION                  Short = C.DCGM_FI_DRIVER_VERSION
	DCGM_FI_NVML_VERSION                    Short = C.DCGM_FI_NVML_VERSION
	DCGM_FI_PROCESS_NAME                    Short = C.DCGM_FI_PROCESS_NAME
	DCGM_FI_DEV_COUNT                       Short = C.DCGM_FI_DEV_COUNT
	DCGM_FI_CUDA_DRIVER_VERSION             Short = C.DCGM_FI_CUDA_DRIVER_VERSION
	DCGM_FI_DEV_NAME                        Short = C.DCGM_FI_DEV_NAME
	DCGM_FI_DEV_BRAND                       Short = C.DCGM_FI_DEV_BRAND
	DCGM_FI_DEV_NVML_INDEX                  Short = C.DCGM_FI_DEV_NVML_INDEX
	DCGM_FI_DEV_SERIAL                      Short = C.DCGM_FI_DEV_SERIAL
	DCGM_FI_DEV_UUID                        Short = C.DCGM_FI_DEV_UUID
	DCGM_FI_DEV_MINOR_NUMBER                Short = C.DCGM_FI_DEV_MINOR_NUMBER
	DCGM_FI_DEV_OEM_INFOROM_VER             Short = C.DCGM_FI_DEV_OEM_INFOROM_VER
	DCGM_FI_DEV_PCI_BUSID                   Short = C.DCGM_FI_DEV_PCI_BUSID
	DCGM_FI_DEV_PCI_COMBINED_ID             Short = C.DCGM_FI_DEV_PCI_COMBINED_ID
	DCGM_FI_DEV_PCI_SUBSYS_ID               Short = C.DCGM_FI_DEV_PCI_SUBSYS_ID
	DCGM_FI_GPU_TOPOLOGY_PCI                Short = C.DCGM_FI_GPU_TOPOLOGY_PCI
	DCGM_FI_GPU_TOPOLOGY_NVLINK             Short = C.DCGM_FI_GPU_TOPOLOGY_NVLINK
	DCGM_FI_GPU_TOPOLOGY_AFFINITY           Short = C.DCGM_FI_GPU_TOPOLOGY_AFFINITY
	DCGM_FI_DEV_CUDA_COMPUTE_CAPABILITY     Short = C.DCGM_FI_DEV_CUDA_COMPUTE_CAPABILITY
	DCGM_FI_DEV_COMPUTE_MODE                Short = C.DCGM_FI_DEV_COMPUTE_MODE
	DCGM_FI_DEV_PERSISTENCE_MODE            Short = C.DCGM_FI_DEV_PERSISTENCE_MODE
	DCGM_FI_DEV_MIG_MODE                    Short = C.DCGM_FI_DEV_MIG_MODE
	DCGM_FI_DEV_CUDA_VISIBLE_DEVICES_STR    Short = C.DCGM_FI_DEV_CUDA_VISIBLE_DEVICES_STR
	DCGM_FI_DEV_MIG_MAX_SLICES              Short = C.DCGM_FI_DEV_MIG_MAX_SLICES
	DCGM_FI_DEV_CPU_AFFINITY_0              Short = C.DCGM_FI_DEV_CPU_AFFINITY_0
	DCGM_FI_DEV_CPU_AFFINITY_1              Short = C.DCGM_FI_DEV_CPU_AFFINITY_1
	DCGM_FI_DEV_CPU_AFFINITY_2              Short = C.DCGM_FI_DEV_CPU_AFFINITY_2
	DCGM_FI_DEV_CPU_AFFINITY_3              Short = C.DCGM_FI_DEV_CPU_AFFINITY_3
	DCGM_FI_DEV_CC_MODE                     Short = C.DCGM_FI_DEV_CC_MODE
	DCGM_FI_DEV_MIG_ATTRIBUTES              Short = C.DCGM_FI_DEV_MIG_ATTRIBUTES
	DCGM_FI_DEV_MIG_GI_INFO                 Short = C.DCGM_FI_DEV_MIG_GI_INFO
	DCGM_FI_DEV_MIG_CI_INFO                 Short = C.DCGM_FI_DEV_MIG_CI_INFO
	DCGM_FI_DEV_ECC_INFOROM_VER             Short = C.DCGM_FI_DEV_ECC_INFOROM_VER
	DCGM_FI_DEV_POWER_INFOROM_VER           Short = C.DCGM_FI_DEV_POWER_INFOROM_VER
	DCGM_FI_DEV_INFOROM_IMAGE_VER           Short = C.DCGM_FI_DEV_INFOROM_IMAGE_VER
	DCGM_FI_DEV_INFOROM_CONFIG_CHECK        Short = C.DCGM_FI_DEV_INFOROM_CONFIG_CHECK
	DCGM_FI_DEV_INFOROM_CONFIG_VALID        Short = C.DCGM_FI_DEV_INFOROM_CONFIG_VALID
	DCGM_FI_DEV_VBIOS_VERSION               Short = C.DCGM_FI_DEV_VBIOS_VERSION
	DCGM_FI_DEV_MEM_AFFINITY_0              Short = C.DCGM_FI_DEV_MEM_AFFINITY_0
	DCGM_FI_DEV_MEM_AFFINITY_1              Short = C.DCGM_FI_DEV_MEM_AFFINITY_1
	DCGM_FI_DEV_MEM_AFFINITY_2              Short = C.DCGM_FI_DEV_MEM_AFFINITY_2
	DCGM_FI_DEV_MEM_AFFINITY_3              Short = C.DCGM_FI_DEV_MEM_AFFINITY_3
	DCGM_FI_DEV_BAR1_TOTAL                  Short = C.DCGM_FI_DEV_BAR1_TOTAL
	DCGM_FI_SYNC_BOOST                      Short = C.DCGM_FI_SYNC_BOOST
	DCGM_FI_DEV_BAR1_USED                   Short = C.DCGM_FI_DEV_BAR1_USED
	DCGM_FI_DEV_BAR1_FREE                   Short = C.DCGM_FI_DEV_BAR1_FREE
	DCGM_FI_DEV_SM_CLOCK                    Short = C.DCGM_FI_DEV_SM_CLOCK
	DCGM_FI_DEV_MEM_CLOCK                   Short = C.DCGM_FI_DEV_MEM_CLOCK
	DCGM_FI_DEV_VIDEO_CLOCK                 Short = C.DCGM_FI_DEV_VIDEO_CLOCK
	DCGM_FI_DEV_APP_SM_CLOCK                Short = C.DCGM_FI_DEV_APP_SM_CLOCK
	DCGM_FI_DEV_APP_MEM_CLOCK               Short = C.DCGM_FI_DEV_APP_MEM_CLOCK
	DCGM_FI_DEV_CLOCK_THROTTLE_REASONS      Short = C.DCGM_FI_DEV_CLOCK_THROTTLE_REASONS
	DCGM_FI_DEV_MAX_SM_CLOCK                Short = C.DCGM_FI_DEV_MAX_SM_CLOCK
	DCGM_FI_DEV_MAX_MEM_CLOCK               Short = C.DCGM_FI_DEV_MAX_MEM_CLOCK
	DCGM_FI_DEV_MAX_VIDEO_CLOCK             Short = C.DCGM_FI_DEV_MAX_VIDEO_CLOCK
	DCGM_FI_DEV_AUTOBOOST                   Short = C.DCGM_FI_DEV_AUTOBOOST
	DCGM_FI_DEV_SUPPORTED_CLOCKS            Short = C.DCGM_FI_DEV_SUPPORTED_CLOCKS
	DCGM_FI_DEV_MEMORY_TEMP                 Short = C.DCGM_FI_DEV_MEMORY_TEMP
	DCGM_FI_DEV_GPU_TEMP                    Short = C.DCGM_FI_DEV_GPU_TEMP
	DCGM_FI_DEV_MEM_MAX_OP_TEMP             Short = C.DCGM_FI_DEV_MEM_MAX_OP_TEMP
	DCGM_FI_DEV_GPU_MAX_OP_TEMP             Short = C.DCGM_FI_DEV_GPU_MAX_OP_TEMP
	DCGM_FI_DEV_POWER_USAGE                 Short = C.DCGM_FI_DEV_POWER_USAGE
	DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION    Short = C.DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION
	DCGM_FI_DEV_POWER_USAGE_INSTANT         Short = C.DCGM_FI_DEV_POWER_USAGE_INSTANT
	DCGM_FI_DEV_SLOWDOWN_TEMP               Short = C.DCGM_FI_DEV_SLOWDOWN_TEMP
	DCGM_FI_DEV_SHUTDOWN_TEMP               Short = C.DCGM_FI_DEV_SHUTDOWN_TEMP
	DCGM_FI_DEV_POWER_MGMT_LIMIT            Short = C.DCGM_FI_DEV_POWER_MGMT_LIMIT
	DCGM_FI_DEV_POWER_MGMT_LIMIT_MIN        Short = C.DCGM_FI_DEV_POWER_MGMT_LIMIT_MIN
	DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX        Short = C.DCGM_FI_DEV_POWER_MGMT_LIMIT_MAX
	DCGM_FI_DEV_POWER_MGMT_LIMIT_DEF        Short = C.DCGM_FI_DEV_POWER_MGMT_LIMIT_DEF
	DCGM_FI_DEV_ENFORCED_POWER_LIMIT        Short = C.DCGM_FI_DEV_ENFORCED_POWER_LIMIT
	DCGM_FI_DEV_PSTATE                      Short = C.DCGM_FI_DEV_PSTATE
	DCGM_FI_DEV_FAN_SPEED                   Short = C.DCGM_FI_DEV_FAN_SPEED
	DCGM_FI_DEV_PCIE_TX_THROUGHPUT          Short = C.DCGM_FI_DEV_PCIE_TX_THROUGHPUT
	DCGM_FI_DEV_PCIE_RX_THROUGHPUT          Short = C.DCGM_FI_DEV_PCIE_RX_THROUGHPUT
	DCGM_FI_DEV_PCIE_REPLAY_COUNTER         Short = C.DCGM_FI_DEV_PCIE_REPLAY_COUNTER
	DCGM_FI_DEV_GPU_UTIL                    Short = C.DCGM_FI_DEV_GPU_UTIL
	DCGM_FI_DEV_MEM_COPY_UTIL               Short = C.DCGM_FI_DEV_MEM_COPY_UTIL
	DCGM_FI_DEV_ACCOUNTING_DATA             Short = C.DCGM_FI_DEV_ACCOUNTING_DATA
	DCGM_FI_DEV_ENC_UTIL                    Short = C.DCGM_FI_DEV_ENC_UTIL
	DCGM_FI_DEV_DEC_UTIL                    Short = C.DCGM_FI_DEV_DEC_UTIL
	DCGM_FI_DEV_XID_ERRORS                  Short = C.DCGM_FI_DEV_XID_ERRORS
	DCGM_FI_DEV_PCIE_MAX_LINK_GEN           Short = C.DCGM_FI_DEV_PCIE_MAX_LINK_GEN
	DCGM_FI_DEV_PCIE_MAX_LINK_WIDTH         Short = C.DCGM_FI_DEV_PCIE_MAX_LINK_WIDTH
	DCGM_FI_DEV_PCIE_LINK_GEN               Short = C.DCGM_FI_DEV_PCIE_LINK_GEN
	DCGM_FI_DEV_PCIE_LINK_WIDTH             Short = C.DCGM_FI_DEV_PCIE_LINK_WIDTH
	DCGM_FI_DEV_POWER_VIOLATION             Short = C.DCGM_FI_DEV_POWER_VIOLATION
	DCGM_FI_DEV_THERMAL_VIOLATION           Short = C.DCGM_FI_DEV_THERMAL_VIOLATION
	DCGM_FI_DEV_SYNC_BOOST_VIOLATION        Short = C.DCGM_FI_DEV_SYNC_BOOST_VIOLATION
	DCGM_FI_DEV_BOARD_LIMIT_VIOLATION       Short = C.DCGM_FI_DEV_BOARD_LIMIT_VIOLATION
	DCGM_FI_DEV_LOW_UTIL_VIOLATION          Short = C.DCGM_FI_DEV_LOW_UTIL_VIOLATION
	DCGM_FI_DEV_RELIABILITY_VIOLATION       Short = C.DCGM_FI_DEV_RELIABILITY_VIOLATION
	DCGM_FI_DEV_TOTAL_APP_CLOCKS_VIOLATION  Short = C.DCGM_FI_DEV_TOTAL_APP_CLOCKS_VIOLATION
	DCGM_FI_DEV_TOTAL_BASE_CLOCKS_VIOLATION Short = C.DCGM_FI_DEV_TOTAL_BASE_CLOCKS_VIOLATION
	DCGM_FI_DEV_FB_TOTAL                    Short = C.DCGM_FI_DEV_FB_TOTAL
	DCGM_FI_DEV_FB_FREE                     Short = C.DCGM_FI_DEV_FB_FREE
	DCGM_FI_DEV_FB_USED                     Short = C.DCGM_FI_DEV_FB_USED
	DCGM_FI_DEV_FB_RESERVED                 Short = C.DCGM_FI_DEV_FB_RESERVED
	DCGM_FI_DEV_FB_USED_PERCENT             Short = C.DCGM_FI_DEV_FB_USED_PERCENT
	DCGM_FI_DEV_ECC_CURRENT                 Short = C.DCGM_FI_DEV_ECC_CURRENT
	DCGM_FI_DEV_ECC_PENDING                 Short = C.DCGM_FI_DEV_ECC_PENDING
	DCGM_FI_DEV_ECC_SBE_VOL_DEV             Short = C.DCGM_FI_DEV_ECC_SBE_VOL_DEV
	DCGM_FI_DEV_ECC_DBE_VOL_DEV             Short = C.DCGM_FI_DEV_ECC_DBE_VOL_DEV
	DCGM_FI_INTERNAL_FIELDS_0_START         Short = C.DCGM_FI_INTERNAL_FIELDS_0_START
	DCGM_FI_INTERNAL_FIELDS_0_END           Short = C.DCGM_FI_INTERNAL_FIELDS_0_END

	DCGM_FI_PROF_GR_ENGINE_ACTIVE   Short = C.DCGM_FI_PROF_GR_ENGINE_ACTIVE
	DCGM_FI_PROF_SM_ACTIVE          Short = C.DCGM_FI_PROF_SM_ACTIVE
	DCGM_FI_PROF_SM_OCCUPANCY       Short = C.DCGM_FI_PROF_SM_OCCUPANCY
	DCGM_FI_PROF_PIPE_TENSOR_ACTIVE Short = C.DCGM_FI_PROF_PIPE_TENSOR_ACTIVE
	DCGM_FI_PROF_DRAM_ACTIVE        Short = C.DCGM_FI_PROF_DRAM_ACTIVE
	DCGM_FI_PROF_PCIE_TX_BYTES      Short = C.DCGM_FI_PROF_PCIE_TX_BYTES
	DCGM_FI_PROF_PCIE_RX_BYTES      Short = C.DCGM_FI_PROF_PCIE_RX_BYTES

	DCGM_FI_MAX_FIELDS Short = C.DCGM_FI_MAX_FIELDS
)
